#!/bin/bash
set -eo pipefail

export PGPASSWORD="${POSTGRES_PASSWORD:-}"

if pg_isready -q -d ${POSTGRES_DB} -h $(hostname -i) -U ${POSTGRES_USER} && check=$? && [ $check = '0' ]; then
      exit 0
   else
      exit 1
fi
